2025-04-06 09:50:28,547 - INFO - server listening on 0.0.0.0:8100
2025-04-06 09:50:28,547 - INFO - WebSocket server started on ws://0.0.0.0:8100
2025-04-06 10:33:54,564 - INFO - connection rejected (426 Upgrade Required)
2025-04-06 10:33:54,584 - ERROR - opening handshake failed
Traceback (most recent call last):
  File "/root/venv/lib/python3.12/site-packages/websockets/asyncio/server.py", line 356, in conn_handler
    await connection.handshake(
  File "/root/venv/lib/python3.12/site-packages/websockets/asyncio/server.py", line 207, in handshake
    raise self.protocol.handshake_exc
  File "/root/venv/lib/python3.12/site-packages/websockets/server.py", line 138, in accept
    ) = self.process_request(request)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venv/lib/python3.12/site-packages/websockets/server.py", line 233, in process_request
    raise InvalidUpgrade(
websockets.exceptions.InvalidUpgrade: invalid Connection header: close
2025-04-06 12:43:41,513 - INFO - connection open
2025-04-06 12:43:41,539 - INFO - Received: Hello Server

2025-04-06 12:43:41,539 - INFO - Sent: Echo: Hello Server

